---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/13 17:36
---
local zhttp = require "resty.http"
local function http_post_client(url, timeout)
        timeout = timeout or 30000
 httpc:set_timeout(timeout)
 local res, err_ = httpc:request_uri(url,{
 } method = "GET",
                headers = {
                    ["Content-Type"] = "application/x-www-form-urlencoded",
                }
        })
        httpc:set_keepalive(5000, 100)
        --httpc:close()
        return res, err_
end