---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/7 16:50
---
---
---
--[[local base = require("kong.plugins.base_plugin")
local ResponseHandler = BasePlugin:extend()
function ResponseHandler:new()
    ResponseHandler.super.new(self, "my-custom-plugin")
end]]
--pcall(function(i) print(i) error('error..') end, 33)
--[[max = function(a,b)
    if  a>b  then
        return a
    else
        return b
    end
end
function test(a,b)
    do
        if true then
            max(a,b)
            error('参数类型错误',1)
        end

    end
end]]
--print(test(10,c))

max = function()
    return 1,2
end
local x,y=4,max()
print(x,y)
a = {z={method=post},x={method=get}}
b={x=1,y=2}
for k,v in pairs(a) do
    print(v.method)
    print(k,v)
end
print(a.z.method)
x= {url = 1,url=2}
print(x.url,x.url)
y= "{url = 1,url=2}"
local cities = {
    { name = 'London', population = 8615246 },
    { name = 'Berlin', population = 3517424 },
    { name = 'Madrid', population = 3165235 },
    { name = 'Rome',   population = 2870528 }
}
print(cities[1].name)
t = {a=2,b=3,c=4}
o = {a=4,b=3,c=4}

function tihuan(a,b)
    for k,v in pairs(a) do
        for x,y in pairs(b) do
            if k==x and type(a)~=number then
                a[k]=y
            end
        end
    end
end
do
    tihuan(t,o)
end
print(t.a)
tablex = {}
table.insert(tablex,1,4)

for k,v in pairs(tablex) do
    print(k,v)
end