---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/10 10:14
---
return {
    postgresql = {
        --id 行标记
        --request 请求路径 （主键）
        --api 请求对应的api服务
        --header 请求的头信息
        --body 请求的body信息
        up = [[
      CREATE TABLE IF NOT EXISTS "responsemap_table" (
        "id"           UUID                         PRIMARY KEY,
        "created_at"   TIMESTAMP WITHOUT TIME ZONE,
        "col1"         TEXT
        "request"      TEXT
        "api"          TEXT
        "header"       TEXT
        "body"         Text
      );

      DO $$
      BEGIN
        CREATE INDEX IF NOT EXISTS "my_plugin_table_request"
                                ON "responsemap_table" ("col1");
      EXCEPTION WHEN UNDEFINED_COLUMN THEN
        -- Do nothing, accept existing state
      END$$;
      DO $$
      BEGIN
      INSERT INTO TABLE_NAME (column1, column2, column3,...columnN)
      VALUES (value1, value2, value3,...valueN)
      END$$;
    ]],
        teardown = function(connector, helpers)
            assert(connector:connect_migrations())
            assert(connector:query("ALTER TABLE responsemap_table DROP col1"))
        end,
    }
}